"""
Spotify Hit Predictor — Training Service
Reads data/spotify_subset.csv (committed to git, generated by create_subset.py)
Predicts whether a track is a hit (popularity >= 70)
"""

import os
import sys
import json
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix
from xgboost import XGBClassifier

DATA_PATH = "/app/data/spotify_subset.csv" if os.path.exists("/app/data/spotify_subset.csv") else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data", "spotify_subset.csv")
EXCHANGE_DIR = "/exchange" if os.path.exists("/exchange") else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "exchange")
MODEL_PATH    = os.path.join(EXCHANGE_DIR, "model.joblib")
SCALER_PATH   = os.path.join(EXCHANGE_DIR, "scaler.joblib")
METRICS_PATH  = os.path.join(EXCHANGE_DIR, "metrics.json")

FEATURES = ["energy", "danceability", "tempo", "valence",
            "loudness", "acousticness", "speechiness"]
TARGET        = "popularity"
HIT_THRESHOLD = 70
RANDOM_STATE  = 42
TEST_SIZE     = 0.2


def load_data():
    if not os.path.exists(DATA_PATH):
        print(f"[error] Dataset not found at {DATA_PATH}")
        print("  Run:  python create_subset.py   (once, locally)")
        print("  Then rebuild:  docker compose up --build")
        sys.exit(1)

    df = pd.read_csv(DATA_PATH)

    if "track_popularity" in df.columns:
        df.rename(columns={"track_popularity": "popularity"}, inplace=True)

    missing = [f for f in FEATURES + [TARGET] if f not in df.columns]
    if missing:
        print(f"[error] Missing columns: {missing}")
        sys.exit(1)

    df = df[FEATURES + [TARGET]].dropna()
    print(f"[data] Loaded {len(df):,} rows")
    return df


def train(df):
    df = df.copy()
    df["hit"] = (df[TARGET] >= HIT_THRESHOLD).astype(int)
    hit_rate = df["hit"].mean()
    print(f"[train] Hit rate: {hit_rate:.1%}  |  rows: {len(df):,}")

    X, y = df[FEATURES].values, df["hit"].values
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )

    scaler  = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test  = scaler.transform(X_test)

    model = XGBClassifier(
        n_estimators=300, max_depth=5, learning_rate=0.05,
        subsample=0.8, colsample_bytree=0.8,
        scale_pos_weight=(y_train == 0).sum() / max((y_train == 1).sum(), 1),
        eval_metric="logloss", random_state=RANDOM_STATE,
        n_jobs=-1, verbosity=0,
    )

    print("[train] Fitting XGBoost …")
    model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)

    y_pred  = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]
    acc     = accuracy_score(y_test, y_pred)
    auc     = roc_auc_score(y_test, y_proba)

    print(f"[eval] Accuracy: {acc:.3f}  |  AUC-ROC: {auc:.3f}")
    print(classification_report(y_test, y_pred, target_names=["Not a hit", "Hit"]))

    metrics = {
        "accuracy":           round(acc, 4),
        "auc_roc":            round(auc, 4),
        "hit_threshold":      HIT_THRESHOLD,
        "hit_rate":           round(float(hit_rate), 4),
        "train_size":         int(len(X_train)),
        "test_size":          int(len(X_test)),
        "feature_importance": dict(zip(FEATURES, model.feature_importances_.tolist())),
        "confusion_matrix":   confusion_matrix(y_test, y_pred).tolist(),
    }
    return model, scaler, metrics


def save_artifacts(model, scaler, metrics):
    os.makedirs(EXCHANGE_DIR, exist_ok=True)
    joblib.dump(model,  MODEL_PATH)
    joblib.dump(scaler, SCALER_PATH)
    with open(METRICS_PATH, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"[save] model.joblib  → {MODEL_PATH}")
    print(f"[save] scaler.joblib → {SCALER_PATH}")
    print(f"[save] metrics.json  → {METRICS_PATH}")


if __name__ == "__main__":
    print("=" * 55)
    print("  Spotify Hit Predictor — Training Service")
    print("=" * 55)
    df                     = load_data()
    model, scaler, metrics = train(df)
    save_artifacts(model, scaler, metrics)
    print("=" * 55)
    print(f"  Done! AUC-ROC: {metrics['auc_roc']}  Accuracy: {metrics['accuracy']}")
    print("=" * 55)
    sys.exit(0)